// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.BFUserDataOnDemand;
import com.cbsd.csg.bf1.domain.BFUserIntegrationTest;
import com.cbsd.csg.bf1.repository.BFUserRepository;
import com.cbsd.csg.bf1.service.BFUserService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BFUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BFUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BFUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BFUserIntegrationTest: @Transactional;
    
    @Autowired
    BFUserDataOnDemand BFUserIntegrationTest.dod;
    
    @Autowired
    BFUserService BFUserIntegrationTest.bFUserService;
    
    @Autowired
    BFUserRepository BFUserIntegrationTest.bFUserRepository;
    
    @Test
    public void BFUserIntegrationTest.testCountAllBFUsers() {
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", dod.getRandomBFUser());
        long count = bFUserService.countAllBFUsers();
        Assert.assertTrue("Counter for 'BFUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BFUserIntegrationTest.testFindBFUser() {
        BFUser obj = dod.getRandomBFUser();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to provide an identifier", id);
        obj = bFUserService.findBFUser(id);
        Assert.assertNotNull("Find method for 'BFUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BFUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BFUserIntegrationTest.testFindAllBFUsers() {
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", dod.getRandomBFUser());
        long count = bFUserService.countAllBFUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'BFUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BFUser> result = bFUserService.findAllBFUsers();
        Assert.assertNotNull("Find all method for 'BFUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BFUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BFUserIntegrationTest.testFindBFUserEntries() {
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", dod.getRandomBFUser());
        long count = bFUserService.countAllBFUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BFUser> result = bFUserService.findBFUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BFUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BFUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BFUserIntegrationTest.testFlush() {
        BFUser obj = dod.getRandomBFUser();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to provide an identifier", id);
        obj = bFUserService.findBFUser(id);
        Assert.assertNotNull("Find method for 'BFUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBFUser(obj);
        Integer currentVersion = obj.getVersion();
        bFUserRepository.flush();
        Assert.assertTrue("Version for 'BFUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BFUserIntegrationTest.testUpdateBFUserUpdate() {
        BFUser obj = dod.getRandomBFUser();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to provide an identifier", id);
        obj = bFUserService.findBFUser(id);
        boolean modified =  dod.modifyBFUser(obj);
        Integer currentVersion = obj.getVersion();
        BFUser merged = bFUserService.updateBFUser(obj);
        bFUserRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BFUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BFUserIntegrationTest.testSaveBFUser() {
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", dod.getRandomBFUser());
        BFUser obj = dod.getNewTransientBFUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BFUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BFUser' identifier to be null", obj.getId());
        try {
            bFUserService.saveBFUser(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        bFUserRepository.flush();
        Assert.assertNotNull("Expected 'BFUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BFUserIntegrationTest.testDeleteBFUser() {
        BFUser obj = dod.getRandomBFUser();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BFUser' failed to provide an identifier", id);
        obj = bFUserService.findBFUser(id);
        bFUserService.deleteBFUser(obj);
        bFUserRepository.flush();
        Assert.assertNull("Failed to remove 'BFUser' with identifier '" + id + "'", bFUserService.findBFUser(id));
    }
    
}
