// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.Author;

privileged aspect Author_Roo_JavaBean {
    
    public String Author.getName() {
        return this.name;
    }
    
    public void Author.setName(String name) {
        this.name = name;
    }
    
}
