// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.AuthorIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AuthorIntegrationTest_Roo_Configurable {
    
    declare @type: AuthorIntegrationTest: @Configurable;
    
}
