// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.AuthorDataOnDemand;
import com.cbsd.csg.bf1.domain.AuthorIntegrationTest;
import com.cbsd.csg.bf1.repository.AuthorRepository;
import com.cbsd.csg.bf1.service.AuthorService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AuthorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AuthorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AuthorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AuthorIntegrationTest: @Transactional;
    
    @Autowired
    AuthorDataOnDemand AuthorIntegrationTest.dod;
    
    @Autowired
    AuthorService AuthorIntegrationTest.authorService;
    
    @Autowired
    AuthorRepository AuthorIntegrationTest.authorRepository;
    
    @Test
    public void AuthorIntegrationTest.testCountAllAuthors() {
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", dod.getRandomAuthor());
        long count = authorService.countAllAuthors();
        Assert.assertTrue("Counter for 'Author' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AuthorIntegrationTest.testFindAuthor() {
        Author obj = dod.getRandomAuthor();
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Author' failed to provide an identifier", id);
        obj = authorService.findAuthor(id);
        Assert.assertNotNull("Find method for 'Author' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Author' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AuthorIntegrationTest.testFindAllAuthors() {
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", dod.getRandomAuthor());
        long count = authorService.countAllAuthors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Author', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Author> result = authorService.findAllAuthors();
        Assert.assertNotNull("Find all method for 'Author' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Author' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AuthorIntegrationTest.testFindAuthorEntries() {
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", dod.getRandomAuthor());
        long count = authorService.countAllAuthors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Author> result = authorService.findAuthorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Author' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Author' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AuthorIntegrationTest.testFlush() {
        Author obj = dod.getRandomAuthor();
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Author' failed to provide an identifier", id);
        obj = authorService.findAuthor(id);
        Assert.assertNotNull("Find method for 'Author' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAuthor(obj);
        Integer currentVersion = obj.getVersion();
        authorRepository.flush();
        Assert.assertTrue("Version for 'Author' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthorIntegrationTest.testUpdateAuthorUpdate() {
        Author obj = dod.getRandomAuthor();
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Author' failed to provide an identifier", id);
        obj = authorService.findAuthor(id);
        boolean modified =  dod.modifyAuthor(obj);
        Integer currentVersion = obj.getVersion();
        Author merged = authorService.updateAuthor(obj);
        authorRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Author' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthorIntegrationTest.testSaveAuthor() {
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", dod.getRandomAuthor());
        Author obj = dod.getNewTransientAuthor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Author' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Author' identifier to be null", obj.getId());
        try {
            authorService.saveAuthor(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        authorRepository.flush();
        Assert.assertNotNull("Expected 'Author' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AuthorIntegrationTest.testDeleteAuthor() {
        Author obj = dod.getRandomAuthor();
        Assert.assertNotNull("Data on demand for 'Author' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Author' failed to provide an identifier", id);
        obj = authorService.findAuthor(id);
        authorService.deleteAuthor(obj);
        authorRepository.flush();
        Assert.assertNull("Failed to remove 'Author' with identifier '" + id + "'", authorService.findAuthor(id));
    }
    
}
