// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.BFUserIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BFUserIntegrationTest_Roo_Configurable {
    
    declare @type: BFUserIntegrationTest: @Configurable;
    
}
