// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.UserAuthorFavouriteDataOnDemand;
import com.cbsd.csg.bf1.domain.UserAuthorFavouriteIntegrationTest;
import com.cbsd.csg.bf1.repository.UserAuthorFavouriteRepository;
import com.cbsd.csg.bf1.service.UserAuthorFavouriteService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAuthorFavouriteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAuthorFavouriteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAuthorFavouriteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAuthorFavouriteIntegrationTest: @Transactional;
    
    @Autowired
    UserAuthorFavouriteDataOnDemand UserAuthorFavouriteIntegrationTest.dod;
    
    @Autowired
    UserAuthorFavouriteService UserAuthorFavouriteIntegrationTest.userAuthorFavouriteService;
    
    @Autowired
    UserAuthorFavouriteRepository UserAuthorFavouriteIntegrationTest.userAuthorFavouriteRepository;
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testCountAllUserAuthorFavourites() {
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", dod.getRandomUserAuthorFavourite());
        long count = userAuthorFavouriteService.countAllUserAuthorFavourites();
        Assert.assertTrue("Counter for 'UserAuthorFavourite' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testFindUserAuthorFavourite() {
        UserAuthorFavourite obj = dod.getRandomUserAuthorFavourite();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to provide an identifier", id);
        obj = userAuthorFavouriteService.findUserAuthorFavourite(id);
        Assert.assertNotNull("Find method for 'UserAuthorFavourite' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAuthorFavourite' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testFindAllUserAuthorFavourites() {
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", dod.getRandomUserAuthorFavourite());
        long count = userAuthorFavouriteService.countAllUserAuthorFavourites();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAuthorFavourite', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAuthorFavourite> result = userAuthorFavouriteService.findAllUserAuthorFavourites();
        Assert.assertNotNull("Find all method for 'UserAuthorFavourite' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAuthorFavourite' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testFindUserAuthorFavouriteEntries() {
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", dod.getRandomUserAuthorFavourite());
        long count = userAuthorFavouriteService.countAllUserAuthorFavourites();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAuthorFavourite> result = userAuthorFavouriteService.findUserAuthorFavouriteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAuthorFavourite' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAuthorFavourite' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testFlush() {
        UserAuthorFavourite obj = dod.getRandomUserAuthorFavourite();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to provide an identifier", id);
        obj = userAuthorFavouriteService.findUserAuthorFavourite(id);
        Assert.assertNotNull("Find method for 'UserAuthorFavourite' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserAuthorFavourite(obj);
        Integer currentVersion = obj.getVersion();
        userAuthorFavouriteRepository.flush();
        Assert.assertTrue("Version for 'UserAuthorFavourite' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testUpdateUserAuthorFavouriteUpdate() {
        UserAuthorFavourite obj = dod.getRandomUserAuthorFavourite();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to provide an identifier", id);
        obj = userAuthorFavouriteService.findUserAuthorFavourite(id);
        boolean modified =  dod.modifyUserAuthorFavourite(obj);
        Integer currentVersion = obj.getVersion();
        UserAuthorFavourite merged = userAuthorFavouriteService.updateUserAuthorFavourite(obj);
        userAuthorFavouriteRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserAuthorFavourite' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testSaveUserAuthorFavourite() {
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", dod.getRandomUserAuthorFavourite());
        UserAuthorFavourite obj = dod.getNewTransientUserAuthorFavourite(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserAuthorFavourite' identifier to be null", obj.getId());
        try {
            userAuthorFavouriteService.saveUserAuthorFavourite(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        userAuthorFavouriteRepository.flush();
        Assert.assertNotNull("Expected 'UserAuthorFavourite' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAuthorFavouriteIntegrationTest.testDeleteUserAuthorFavourite() {
        UserAuthorFavourite obj = dod.getRandomUserAuthorFavourite();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuthorFavourite' failed to provide an identifier", id);
        obj = userAuthorFavouriteService.findUserAuthorFavourite(id);
        userAuthorFavouriteService.deleteUserAuthorFavourite(obj);
        userAuthorFavouriteRepository.flush();
        Assert.assertNull("Failed to remove 'UserAuthorFavourite' with identifier '" + id + "'", userAuthorFavouriteService.findUserAuthorFavourite(id));
    }
    
}
