// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cbsd.csg.bf1.domain;

import com.cbsd.csg.bf1.domain.AuthorDataOnDemand;
import com.cbsd.csg.bf1.domain.BFUserDataOnDemand;
import com.cbsd.csg.bf1.domain.UserAuthorFavourite;
import com.cbsd.csg.bf1.domain.UserAuthorFavouriteDataOnDemand;
import com.cbsd.csg.bf1.repository.UserAuthorFavouriteRepository;
import com.cbsd.csg.bf1.service.UserAuthorFavouriteService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UserAuthorFavouriteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserAuthorFavouriteDataOnDemand: @Component;
    
    private Random UserAuthorFavouriteDataOnDemand.rnd = new SecureRandom();
    
    private List<UserAuthorFavourite> UserAuthorFavouriteDataOnDemand.data;
    
    @Autowired
    AuthorDataOnDemand UserAuthorFavouriteDataOnDemand.authorDataOnDemand;
    
    @Autowired
    BFUserDataOnDemand UserAuthorFavouriteDataOnDemand.bFUserDataOnDemand;
    
    @Autowired
    UserAuthorFavouriteService UserAuthorFavouriteDataOnDemand.userAuthorFavouriteService;
    
    @Autowired
    UserAuthorFavouriteRepository UserAuthorFavouriteDataOnDemand.userAuthorFavouriteRepository;
    
    public UserAuthorFavourite UserAuthorFavouriteDataOnDemand.getNewTransientUserAuthorFavourite(int index) {
        UserAuthorFavourite obj = new UserAuthorFavourite();
        return obj;
    }
    
    public UserAuthorFavourite UserAuthorFavouriteDataOnDemand.getSpecificUserAuthorFavourite(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserAuthorFavourite obj = data.get(index);
        Long id = obj.getId();
        return userAuthorFavouriteService.findUserAuthorFavourite(id);
    }
    
    public UserAuthorFavourite UserAuthorFavouriteDataOnDemand.getRandomUserAuthorFavourite() {
        init();
        UserAuthorFavourite obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return userAuthorFavouriteService.findUserAuthorFavourite(id);
    }
    
    public boolean UserAuthorFavouriteDataOnDemand.modifyUserAuthorFavourite(UserAuthorFavourite obj) {
        return false;
    }
    
    public void UserAuthorFavouriteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = userAuthorFavouriteService.findUserAuthorFavouriteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserAuthorFavourite' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserAuthorFavourite>();
        for (int i = 0; i < 10; i++) {
            UserAuthorFavourite obj = getNewTransientUserAuthorFavourite(i);
            try {
                userAuthorFavouriteService.saveUserAuthorFavourite(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            userAuthorFavouriteRepository.flush();
            data.add(obj);
        }
    }
    
}
